vich_uploader:
    db_driver: orm

    mappings:
        case_before:
            uri_prefix: /uploads/cases/before
            upload_destination: '%kernel.project_dir%/public/uploads/cases/before'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        case_after:
            uri_prefix: /uploads/cases/after
            upload_destination: '%kernel.project_dir%/public/uploads/cases/after'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        case_gallery:
            uri_prefix: /uploads/cases/gallery
            upload_destination: '%kernel.project_dir%/public/uploads/cases/gallery'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        package_images:
            uri_prefix: /uploads/packages
            upload_destination: '%kernel.project_dir%/public/uploads/packages'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        hero_before:
            uri_prefix: /uploads/cases/before
            upload_destination: '%kernel.project_dir%/public/uploads/cases/before'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false

        hero_after:
            uri_prefix: /uploads/cases/after
            upload_destination: '%kernel.project_dir%/public/uploads/cases/after'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false
