# ==========================================================
#  PROD DOMAIN HTTP -> HTTPS
# ==========================================================
server {
    listen 80;
    server_name remod-remont.ru www.remod-remont.ru;

    return 301 https://$host$request_uri;
}

# ==========================================================
#  PROD DOMAIN HTTPS
# ==========================================================
server {
    listen 443 ssl;
    server_name remod-remont.ru www.remod-remont.ru;
    root /var/www/html/public;
    client_max_body_size 20M;

    ssl_certificate /etc/letsencrypt/live/remod-remont.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/remod-remont.ru/privkey.pem;

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # --------------------------------------------------
    #  1. Symfony  (API, админка, авторизация)
    # --------------------------------------------------
    location ~ ^/api(/|$) {
        try_files $uri /index.php?$query_string;
    }

    # --------------------------------------------------
    #  2. Статика  (загрузки, картинки, кэш ресайзов)
    # --------------------------------------------------
    location /uploads/ {
        try_files $uri =404;
    }

    location ~* ^/media/cache/resolve/ {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param REQUEST_URI $uri;
    }

    location ~* ^/media/cache/ {
        try_files $uri @imagine_resolve_ssl;
    }

    location @imagine_resolve_ssl {
        rewrite ^/media/cache/(.*)$ /media/cache/resolve/$1 last;
    }

    # --------------------------------------------------
    #  3. PHP-FPM
    # --------------------------------------------------
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # --------------------------------------------------
    #  4. Фронтенд  (React SPA из dist/)
    # --------------------------------------------------
    location / {
        root /var/www/frontend;
        try_files $uri /index.html;
    }
}
