<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325154543 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE case_gallery_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_name VARCHAR(255) DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, renovation_case_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4649572484B37062 ON case_gallery_image (renovation_case_id)');
        $this->addSql('CREATE TABLE faq (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question VARCHAR(500) NOT NULL, answer TEXT NOT NULL, sort_order INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE lead (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) DEFAULT \'QUIZ\' NOT NULL, property_type VARCHAR(100) DEFAULT NULL, area VARCHAR(50) DEFAULT NULL, package VARCHAR(100) DEFAULT NULL, timeframe VARCHAR(100) DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE package (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, sub VARCHAR(150) NOT NULL, description TEXT NOT NULL, for_who JSON NOT NULL, includes JSON NOT NULL, levels JSON DEFAULT NULL, price VARCHAR(50) NOT NULL, featured BOOLEAN DEFAULT false NOT NULL, image_name VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DE686795989D9B62 ON package (slug)');
        $this->addSql('CREATE TABLE renovation_case (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, title VARCHAR(255) NOT NULL, area VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, pkg VARCHAR(100) NOT NULL, days INT NOT NULL, year INT NOT NULL, summary TEXT NOT NULL, challenges JSON NOT NULL, img_before_name VARCHAR(255) DEFAULT NULL, img_after_name VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_39F23E9A989D9B62 ON renovation_case (slug)');
        $this->addSql('CREATE TABLE site_contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, phone VARCHAR(30) NOT NULL, whatsapp VARCHAR(100) DEFAULT NULL, telegram VARCHAR(100) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, hours_weekday VARCHAR(50) DEFAULT NULL, hours_saturday VARCHAR(50) DEFAULT NULL, hours_sunday VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE testimonial (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, obj VARCHAR(150) NOT NULL, pkg VARCHAR(100) NOT NULL, stars INT DEFAULT 5 NOT NULL, quote TEXT NOT NULL, sort_order INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, login VARCHAR(100) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_LOGIN ON "user" (login)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE case_gallery_image ADD CONSTRAINT FK_4649572484B37062 FOREIGN KEY (renovation_case_id) REFERENCES renovation_case (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE case_gallery_image DROP CONSTRAINT FK_4649572484B37062');
        $this->addSql('DROP TABLE case_gallery_image');
        $this->addSql('DROP TABLE faq');
        $this->addSql('DROP TABLE lead');
        $this->addSql('DROP TABLE package');
        $this->addSql('DROP TABLE renovation_case');
        $this->addSql('DROP TABLE site_contact');
        $this->addSql('DROP TABLE testimonial');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
