<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260402123000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE home_hero (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, kicker_text VARCHAR(255) DEFAULT \'\' NOT NULL, title_top VARCHAR(255) DEFAULT \'\' NOT NULL, title_accent TEXT DEFAULT \'\' NOT NULL, subtitle_text TEXT DEFAULT \'\' NOT NULL, badge_text VARCHAR(255) DEFAULT \'\' NOT NULL, before_label_text VARCHAR(50) DEFAULT \'До\' NOT NULL, primary_cta_text VARCHAR(255) DEFAULT \'\' NOT NULL, primary_cta_url VARCHAR(255) DEFAULT \'\' NOT NULL, secondary_cta_text VARCHAR(255) DEFAULT \'\' NOT NULL, secondary_cta_url VARCHAR(255) DEFAULT \'\' NOT NULL, utp1_label VARCHAR(100) DEFAULT \'\' NOT NULL, utp1_desc TEXT DEFAULT \'\' NOT NULL, utp2_label VARCHAR(100) DEFAULT \'\' NOT NULL, utp2_desc TEXT DEFAULT \'\' NOT NULL, utp3_label VARCHAR(100) DEFAULT \'\' NOT NULL, utp3_desc TEXT DEFAULT \'\' NOT NULL, before_alt VARCHAR(255) DEFAULT \'\' NOT NULL, after_alt VARCHAR(255) DEFAULT \'\' NOT NULL, img_before_name VARCHAR(255) DEFAULT NULL, img_after_name VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');

        $this->addSql('INSERT INTO home_hero (enabled, kicker_text, title_top, title_accent, subtitle_text, badge_text, before_label_text, primary_cta_text, primary_cta_url, secondary_cta_text, secondary_cta_url, utp1_label, utp1_desc, utp2_label, utp2_desc, utp3_label, utp3_desc, before_alt, after_alt, img_before_name, img_after_name, updated_at) VALUES (true, \'Принимаем заявки · Москва и МО\', \'Ремонт под ключ.\', \'90 дней — и можно заезжать.\', \'Берём на себя всё: замеры, материалы, команду, контроль и клининг. Цена и срок — в договоре до начала работ.\', \'Белый · Комфорт · 84 дня\', \'До\', \'Узнать стоимость за 10 минут\', \'/ocenka\', \'Посмотреть кейсы\', \'/kejsy\', \'90 дней\', \'Фиксированный срок. Сдаём в дату из договора — или согласуем перенос заранее.\', \'Цена в договоре\', \'Итоговая стоимость фиксируется до начала. Никаких «внезапных доплат».\', \'Рассрочка\', \'Разбиваем платёж на части. Уточняем условия на первой встрече.\', \'До ремонта\', \'Современный интерьер после ремонта\', \'before-02.jpg\', \'after-01.jpg\', NULL)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE home_hero');
    }
}

